# Generated by Django 4.0.3 on 2022-03-26 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInMind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('project_image', models.ImageField(default='coming_soon.png', upload_to='project_in_mind_pics')),
                ('project_demo_video', embed_video.fields.EmbedVideoField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Project In Mind',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('project_description', models.TextField()),
                ('project_github_link', models.CharField(max_length=255)),
                ('project_live_link', models.CharField(blank=True, max_length=255, null=True)),
                ('project_image', models.ImageField(default='coming_soon.png.png', upload_to='project_pics')),
                ('project_demo_video', embed_video.fields.EmbedVideoField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='frontend.category')),
            ],
        ),
    ]
